### ISSUE TITLE
Incorporate FAST subject selection into CORE

### ISSUE THREAD

**Issue by amareshjoshi** [MESH-Research/humcore#139]
Incorporate FAST subject selection into CORE repository upload.

- [x] Write test of subject select with editing
- [x] Test sample code with commons version of jselect (4.0.0)
- [x] Make changes to user (initial) deposit page (initial user deposit)
- [x] Make changes to user edit deposit page (user edit of deposit)
- [x] Make changes deposits listing pages (lookup (link) deposits by subject)
- [x] Make changes to user deposit review page (review page after any changes
- [x] Make changes to deposit by administrators
